#!/bin/bash
# ============================================================================
# LifeDash Demo — FFmpeg Post-Processing
#
# Adds text overlays to the raw demo capture to match the storyboard.
# Also generates the hook/CTA intro and outro title cards.
#
# Prerequisites:
#   - ffmpeg in PATH (with drawtext filter — included in standard builds)
#   - Raw video at docs/demo-raw.mp4 (generated by scripts/record-demo.mjs)
#
# Usage:
#   bash scripts/demo-overlay.sh              # full demo
#   bash scripts/demo-overlay.sh --short      # 30-second cut
#   bash scripts/demo-overlay.sh --gif        # also export GIF
#
# Output:
#   docs/demo-final.mp4     — complete demo with overlays
#   docs/demo.gif           — GIF version (if --gif flag used)
# ============================================================================

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
DOCS="$ROOT/docs"

RAW="$DOCS/demo-raw.mp4"
INTRO="$DOCS/demo-intro.mp4"
OUTRO="$DOCS/demo-outro.mp4"
OVERLAID="$DOCS/demo-overlaid.mp4"
FINAL="$DOCS/demo-final.mp4"
CONCAT_LIST="$DOCS/demo-concat.txt"

SHORT=false
MAKE_GIF=false

for arg in "$@"; do
  case $arg in
    --short) SHORT=true ;;
    --gif)   MAKE_GIF=true ;;
  esac
done

# Check prerequisites
if [ ! -f "$RAW" ]; then
  echo "Error: Raw video not found at $RAW"
  echo "Run 'node scripts/record-demo.mjs' first."
  exit 1
fi

if ! command -v ffmpeg &> /dev/null; then
  echo "Error: ffmpeg not found in PATH."
  exit 1
fi

# Get video dimensions from raw capture
WIDTH=$(ffprobe -v error -select_streams v:0 -show_entries stream=width -of csv=p=0 "$RAW")
HEIGHT=$(ffprobe -v error -select_streams v:0 -show_entries stream=height -of csv=p=0 "$RAW")
echo "Raw video: ${WIDTH}x${HEIGHT}"

# ============================================================================
# Step 1: Generate intro title card (Scene 1 — Hook)
# ============================================================================
echo ""
echo "Step 1: Generating intro title card..."

if $SHORT; then
  # Short version: single title
  ffmpeg -y -f lavfi -i "color=c=black:s=${WIDTH}x${HEIGHT}:d=3" \
    -vf "drawtext=text='Meetings. Transcribed. Private.':fontsize=56:fontcolor=white:x=(w-text_w)/2:y=(h-text_h)/2:font='Segoe UI'" \
    -c:v libx264 -pix_fmt yuv420p -t 3 "$INTRO" 2>/dev/null
else
  # Full version: two-part hook
  # Part A: "Your meetings are being uploaded to someone else's server." (3s)
  # Part B: "What if they didn't have to be?" (2s)
  ffmpeg -y -f lavfi -i "color=c=black:s=${WIDTH}x${HEIGHT}:d=5" \
    -vf "\
      drawtext=text='Your meetings are being uploaded':fontsize=48:fontcolor=white:x=(w-text_w)/2:y=(h-text_h)/2-30:font='Segoe UI':enable='lt(t,3)',\
      drawtext=text='to someone else'\''s server.':fontsize=48:fontcolor=white:x=(w-text_w)/2:y=(h-text_h)/2+30:font='Segoe UI':enable='lt(t,3)',\
      drawtext=text='What if they didn'\''t have to be?':fontsize=48:fontcolor=white:x=(w-text_w)/2:y=(h-text_h)/2:font='Segoe UI':enable='gte(t,3)'" \
    -c:v libx264 -pix_fmt yuv420p -t 5 "$INTRO" 2>/dev/null
fi

echo "  Done: $INTRO"

# ============================================================================
# Step 2: Add text overlays to raw footage
# ============================================================================
echo ""
echo "Step 2: Adding text overlays to raw footage..."

# Get duration of raw video
DURATION=$(ffprobe -v error -show_entries format=duration -of csv=p=0 "$RAW" | cut -d. -f1)
echo "  Raw duration: ${DURATION}s"

# Calculate scene timestamps based on raw video duration
# Overlay text appears as a semi-transparent bar at the bottom
OVERLAY_FILTER="\
drawbox=x=0:y=ih-80:w=iw:h=80:color=black@0.6:t=fill,\
drawtext=text='LifeDash records your meetings locally. Nothing leaves your machine.':fontsize=22:fontcolor=white:x=(w-text_w)/2:y=h-55:font='Segoe UI':enable='lt(t,12)',\
drawtext=text='Transcribed on-device with Whisper. No cloud. No third party.':fontsize=22:fontcolor=white:x=(w-text_w)/2:y=h-55:font='Segoe UI':enable='between(t,12,22)',\
drawtext=text='AI generates a structured brief — summary, decisions, action items.':fontsize=22:fontcolor=white:x=(w-text_w)/2:y=h-55:font='Segoe UI':enable='between(t,22,35)',\
drawtext=text='Action items become tasks on your board. One click.':fontsize=22:fontcolor=white:x=(w-text_w)/2:y=h-55:font='Segoe UI':enable='between(t,35,48)',\
drawtext=text='Plus: AI brainstorming, focus timer, idea capture.':fontsize=22:fontcolor=white:x=(w-text_w)/2:y=h-55:font='Segoe UI':enable='gte(t,48)'"

if $SHORT; then
  OVERLAY_FILTER="\
drawbox=x=0:y=ih-80:w=iw:h=80:color=black@0.6:t=fill,\
drawtext=text='Records and transcribes meetings locally.':fontsize=22:fontcolor=white:x=(w-text_w)/2:y=h-55:font='Segoe UI':enable='lt(t,8)',\
drawtext=text='AI extracts briefs and action items.':fontsize=22:fontcolor=white:x=(w-text_w)/2:y=h-55:font='Segoe UI':enable='between(t,8,18)',\
drawtext=text='Action items flow to your project board.':fontsize=22:fontcolor=white:x=(w-text_w)/2:y=h-55:font='Segoe UI':enable='gte(t,18)'"
fi

ffmpeg -y -i "$RAW" \
  -vf "$OVERLAY_FILTER" \
  -c:v libx264 -preset medium -crf 20 -pix_fmt yuv420p \
  -c:a copy \
  "$OVERLAID" 2>/dev/null

echo "  Done: $OVERLAID"

# ============================================================================
# Step 3: Generate outro title card (Scene 7 — CTA)
# ============================================================================
echo ""
echo "Step 3: Generating outro title card..."

if $SHORT; then
  OUTRO_DUR=3
else
  OUTRO_DUR=7
fi

ffmpeg -y -f lavfi -i "color=c=black:s=${WIDTH}x${HEIGHT}:d=${OUTRO_DUR}" \
  -vf "\
    drawtext=text='100%% local. 100%% private.':fontsize=40:fontcolor=white:x=(w-text_w)/2:y=(h-text_h)/2-80:font='Segoe UI':enable='gte(t,0.5)',\
    drawtext=text='Free and open source.':fontsize=32:fontcolor=white:x=(w-text_w)/2:y=(h-text_h)/2-10:font='Segoe UI':enable='gte(t,1.5)',\
    drawtext=text='LifeDash':fontsize=64:fontcolor=white:x=(w-text_w)/2:y=(h-text_h)/2+60:font='Segoe UI':fontcolor=white:enable='gte(t,2.5)',\
    drawtext=text='github.com/Lab-51/lifedash':fontsize=24:fontcolor=0x00d4ff:x=(w-text_w)/2:y=(h-text_h)/2+140:font='Segoe UI':enable='gte(t,3.5)'" \
  -c:v libx264 -pix_fmt yuv420p -t ${OUTRO_DUR} "$OUTRO" 2>/dev/null

echo "  Done: $OUTRO"

# ============================================================================
# Step 4: Concatenate intro + overlaid footage + outro
# ============================================================================
echo ""
echo "Step 4: Concatenating segments..."

cat > "$CONCAT_LIST" << EOF
file '$(basename "$INTRO")'
file '$(basename "$OVERLAID")'
file '$(basename "$OUTRO")'
EOF

ffmpeg -y -f concat -safe 0 -i "$CONCAT_LIST" \
  -c:v libx264 -preset medium -crf 20 -pix_fmt yuv420p \
  "$FINAL" 2>/dev/null

echo "  Done: $FINAL"

# ============================================================================
# Step 5: Optional GIF export
# ============================================================================

if $MAKE_GIF; then
  echo ""
  echo "Step 5: Exporting GIF..."
  GIF="$DOCS/demo.gif"

  # Generate palette for better GIF quality
  ffmpeg -y -i "$FINAL" \
    -vf "fps=15,scale=960:-1:flags=lanczos,palettegen=stats_mode=diff" \
    "$DOCS/palette.png" 2>/dev/null

  ffmpeg -y -i "$FINAL" -i "$DOCS/palette.png" \
    -lavfi "fps=15,scale=960:-1:flags=lanczos[x];[x][1:v]paletteuse=dither=bayer:bayer_scale=3" \
    "$GIF" 2>/dev/null

  rm -f "$DOCS/palette.png"
  GIF_SIZE=$(du -h "$GIF" | cut -f1)
  echo "  Done: $GIF ($GIF_SIZE)"
fi

# ============================================================================
# Cleanup temp files
# ============================================================================
rm -f "$INTRO" "$OUTRO" "$OVERLAID" "$CONCAT_LIST"

# ============================================================================
# Summary
# ============================================================================
FINAL_SIZE=$(du -h "$FINAL" | cut -f1)
FINAL_DUR=$(ffprobe -v error -show_entries format=duration -of csv=p=0 "$FINAL" | cut -d. -f1)

echo ""
echo "========================================="
echo "  Demo video complete!"
echo "========================================="
echo "  File:     $FINAL"
echo "  Size:     $FINAL_SIZE"
echo "  Duration: ${FINAL_DUR}s"
echo ""
echo "To add to README:"
echo '  ![LifeDash Demo](docs/demo.gif)'
echo ""
echo "To convert to GIF later:"
echo "  bash scripts/demo-overlay.sh --gif"
echo ""
